name: check-build-cross
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          ## linux gnu
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - i686-pc-windows-gnu

          - x86_64-unknown-linux-gnu
          - x86_64-unknown-freebsd
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-linux-android

          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi

          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          - armv7-unknown-linux-ohos
          - armv7-unknown-linux-ohos

          - aarch64-unknown-linux-gnu
          - aarch64-pc-windows-msvc
          - aarch64-pc-windows-gnullvm
          - aarch64-linux-android
          - aarch64-apple-darwin
          - aarch64-unknown-linux-musl
          - aarch64-unknown-linux-ohos

          - loongarch64-unknown-linux-gnu

          - s390x-unknown-linux-gnu

          - sparcv9-sun-solaris

          - loongarch64-unknown-linux-musl

          - riscv64gc-unknown-linux-musl

          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - powerpc64le-unknown-linux-musl

    env:
      CROSS_NO_WARNINGS: 0

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup env
        run: |
          sudo apt update -y
          sudo apt install libclang-dev -y

      - name: install Rust 1.89.0
        uses: dtolnay/rust-toolchain@1.89.0

      - name: Install Rust Nightly
        if: ${{ contains(matrix.target, 'mips') }}
        uses: dtolnay/rust-toolchain@nightly

      - name: Install xwin
        if: ${{ contains(matrix.target, 'msvc') }}
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-xwin
          version: "0.19.2"

      - name: Install cross
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cross
          git: https://github.com/cross-rs/cross

      - name: Install rust target
        run: |
          rustup target add ${{ matrix.target }}

      - name: build package for msvc
        if: ${{ contains(matrix.target, 'msvc') }}
        env:
          XWIN_CROSS_COMPILER: clang
        run: |
          cargo xwin build --target=${{ matrix.target }} -p crown
          cargo xwin build --target=${{ matrix.target }} -p crown -F std

      - name: build package for ${{ matrix.target }}
        if: ${{ !contains(matrix.target, 'mips') && !contains(matrix.target, 'msvc') }}
        run: |
          cross build --target=${{ matrix.target }} -p crown
          cross build --target=${{ matrix.target }} -p crown -F std

      - name: build package for mips
        if: ${{ contains(matrix.target, 'mips') }}
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          RUSTFLAGS="-Zpanic_abort_tests" cross +nightly build --target=${{ matrix.target }} -Z build-std=std,panic_abort
